[project]
name = "2025-FTP-project"
version = "0.1.0"
description = "Bitcoin trading algo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
]
